"""
Uses the Anthropic API to turn a reconstructed decision-path timeline into:
  1. A plain-English summary for a non-technical reviewer / the affected person.
  2. (Bonus) A draft response to a regulatory challenge, grounded in the
     specific data considered.

Both prompts are deliberately constrained to "explain only what is in this
timeline" to avoid the model inventing reasoning that wasn't actually part
of the audited decision -- that would defeat the purpose of an audit tool.

When ANTHROPIC_API_KEY is set (or passed via the X-API-Key header), summaries
are generated by Claude. Otherwise a local fallback builds plain-English text
directly from the timeline JSON — no API key required.
"""
from __future__ import annotations

import json
import os
from typing import Any, Optional

MODEL = "claude-sonnet-4-6"

_SUMMARY_SYSTEM_PROMPT = """You are writing a plain-English explanation of an automated decision \
for a non-technical reviewer or for the person the decision was made about.

Rules:
- Base your explanation ONLY on the timeline JSON provided. Do not invent facts, data, or \
reasoning that is not present in the timeline.
- Explain, in order: what was requested, what data/context was looked up, what the reasoning \
was, and what the final decision was and why.
- Avoid jargon (no "tool_call", "session_id", internal rule IDs, etc.) -- translate these into \
plain language a customer could understand.
- Keep it concise: 4-8 sentences.
- If the timeline shows redacted fields, do not speculate about what the redacted value was.
- Be neutral and factual, not defensive or apologetic."""

_CHALLENGE_SYSTEM_PROMPT = """You are drafting a response to a regulatory challenge or appeal \
regarding an automated decision. The response will be reviewed by a compliance officer before \
being sent.

Rules:
- Base your response ONLY on the timeline JSON provided. Cite the specific data points, tool \
calls, and reasoning steps that were used, by referring to them concretely (e.g. "a credit \
bureau lookup was performed on [date]" rather than vague claims).
- Do not invent facts, data, or reasoning not present in the timeline.
- Structure the response as: (1) summary of the request, (2) the data considered, (3) the \
decision logic applied, (4) the final decision and the specific rule/threshold that drove it.
- Do not restate any values marked as redacted; instead note that the underlying record exists \
and can be reviewed under appropriate access controls.
- Professional, precise tone suitable for a compliance/regulatory audience."""


def _api_key(passed_api_key: Optional[str] = None) -> Optional[str]:
    return passed_api_key or os.environ.get("ANTHROPIC_API_KEY")


def _get_client(passed_api_key: Optional[str] = None):
    try:
        import anthropic
    except ImportError as e:
        raise RuntimeError(
            "The 'anthropic' package is required for LLM summaries. "
            "Install with: pip install anthropic"
        ) from e

    api_key = _api_key(passed_api_key)
    if not api_key:
        raise RuntimeError("No API key available.")
    return anthropic.Anthropic(api_key=api_key)


def _events(timeline: dict[str, Any], event_type: str) -> list[dict[str, Any]]:
    return [e for e in timeline.get("timeline", []) if e.get("event_type") == event_type]


def _humanize_tool_name(name: str) -> str:
    return name.replace("_", " ")


def _generate_offline_summary(timeline: dict[str, Any]) -> str:
    parts: list[str] = []

    input_events = _events(timeline, "input")
    if input_events:
        inp = input_events[0].get("payload", {}).get("input", {})
        request_type = str(inp.get("request_type", "request")).replace("_", " ")
        ref = inp.get("application_id") or inp.get("request_id") or "the submitted request"
        parts.append(f"A {request_type} was received (reference: {ref}).")

    tool_calls = _events(timeline, "tool_call")
    if tool_calls:
        names = [_humanize_tool_name(e.get("payload", {}).get("tool_name", "external lookup")) for e in tool_calls]
        parts.append(f"The system retrieved data via: {', '.join(names)}.")

    context_events = _events(timeline, "context_retrieved")
    if context_events:
        source = str(context_events[0].get("payload", {}).get("source", "internal records")).replace("_", " ")
        parts.append(f"Applicable policy criteria were loaded from {source}.")

    reasoning_events = _events(timeline, "reasoning_step")
    if reasoning_events:
        thoughts = [
            e.get("payload", {}).get("thought") or e.get("summary", "")
            for e in reasoning_events
            if e.get("payload", {}).get("thought") or e.get("summary")
        ]
        if thoughts:
            parts.append(" ".join(thoughts))

    decision_events = _events(timeline, "decision")
    if decision_events:
        payload = decision_events[0].get("payload", {})
        decision = payload.get("decision", "UNKNOWN")
        reasoning = payload.get("reasoning", "")
        rule_id = payload.get("rule_id")
        rule_note = f" (rule: {rule_id})" if rule_id else ""
        parts.append(f"The final decision was {decision}{rule_note}. {reasoning}".strip())

    output_events = _events(timeline, "output")
    if output_events:
        output_text = output_events[0].get("payload", {}).get("output")
        if output_text:
            parts.append(f'The message shown to the applicant was: "{output_text}"')

    if not parts:
        return "No decision-path events were found in this timeline."

    return " ".join(parts)


def _generate_offline_challenge_response(
    timeline: dict[str, Any], challenge_text: Optional[str] = None
) -> str:
    sections: list[str] = []

    if challenge_text:
        sections.append(f"Re: {challenge_text.strip()}\n")

    input_events = _events(timeline, "input")
    if input_events:
        inp = input_events[0].get("payload", {}).get("input", {})
        request_type = str(inp.get("request_type", "request")).replace("_", " ")
        ref = inp.get("application_id") or inp.get("request_id") or "N/A"
        sections.append(f"1. Request summary\nA {request_type} was processed (reference: {ref}).")

    data_lines: list[str] = []
    for event in _events(timeline, "tool_call"):
        tool = _humanize_tool_name(event.get("payload", {}).get("tool_name", "lookup"))
        data_lines.append(f"- {tool.capitalize()} was performed. Personal identifiers in the response were redacted in the audit record.")
    for event in _events(timeline, "context_retrieved"):
        source = str(event.get("payload", {}).get("source", "internal policy records")).replace("_", " ")
        data = event.get("payload", {}).get("data", {})
        if data:
            criteria = ", ".join(f"{k.replace('_', ' ')}: {v}" for k, v in data.items())
            data_lines.append(f"- Policy criteria from {source}: {criteria}.")
        else:
            data_lines.append(f"- Policy criteria were retrieved from {source}.")
    if data_lines:
        sections.append("2. Data considered\n" + "\n".join(data_lines))

    logic_lines = [
        e.get("payload", {}).get("thought") or e.get("summary", "")
        for e in _events(timeline, "reasoning_step")
        if e.get("payload", {}).get("thought") or e.get("summary")
    ]
    if logic_lines:
        sections.append("3. Decision logic applied\n" + " ".join(logic_lines))

    decision_events = _events(timeline, "decision")
    if decision_events:
        payload = decision_events[0].get("payload", {})
        decision = payload.get("decision", "UNKNOWN")
        reasoning = payload.get("reasoning", "")
        rule_id = payload.get("rule_id")
        rule_line = f" Rule applied: {rule_id}." if rule_id else ""
        sections.append(
            f"4. Final decision\nThe decision was {decision}.{rule_line} {reasoning}".strip()
        )

    return "\n\n".join(sections) if sections else "No decision-path events were found in this timeline."


def _timeline_json(timeline: dict[str, Any]) -> str:
    return json.dumps(timeline, indent=2, default=str)


def generate_decision_summary(timeline: dict[str, Any], api_key: Optional[str] = None) -> str:
    if not _api_key(api_key):
        return _generate_offline_summary(timeline)

    client = _get_client(api_key)
    message = client.messages.create(
        model=MODEL,
        max_tokens=600,
        system=_SUMMARY_SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": f"Here is the decision path timeline:\n\n{_timeline_json(timeline)}\n\n"
                "Write the plain-English explanation.",
            }
        ],
    )
    return "".join(block.text for block in message.content if block.type == "text").strip()


def generate_challenge_response(
    timeline: dict[str, Any], challenge_text: Optional[str] = None, api_key: Optional[str] = None
) -> str:
    if not _api_key(api_key):
        return _generate_offline_challenge_response(timeline, challenge_text=challenge_text)

    client = _get_client(api_key)
    user_content = f"Here is the decision path timeline:\n\n{_timeline_json(timeline)}\n\n"
    if challenge_text:
        user_content += f"The customer/regulator raised the following challenge:\n{challenge_text}\n\n"
    user_content += "Draft the regulatory challenge response."

    message = client.messages.create(
        model=MODEL,
        max_tokens=900,
        system=_CHALLENGE_SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_content}],
    )
    return "".join(block.text for block in message.content if block.type == "text").strip()
